# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base    = ""
  publish = "build/"
  command = "if [ $IGNORE_WARNING ]; then npm run build; else npm run build-with-warnings; fi"

[[redirects]]
  from = "/*"
  to = "public/index.html"
  status = 200